---


- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  tasks:
  - name: Populate /etc/environment
    lineinfile:
      path: "/etc/environment"
      state: present
      regexp: "^{{ item.key }}="
      line: "{{ item.key }}={{ item.value}}"
    with_items: "{{ os_environment }}"
  vars:
    os_environment:
    - key: ANSIBLE_LOCALHOST_WARNING
      value: "false"
    - key: JENKINS_HOME
      value: '"/var/lib/jenkins"'
