FROM jenkins/jenkins:lts-jdk11
MAINTAINER   Phuc K Nguyen <phucknguyen@gmail.com>

# Skip initial UI setup
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

# Path to custom jenkins config (for the Configuration as Code plugin)
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml

# Initial user
ENV JENKINS_ADMIN_ID admin
ENV JENKINS_ADMIN_PASSWORD admin

# Install plugins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
# TODO: jenkins-plugin-cli is the replacement for install-plugins but for some reason not work for this yet
# RUN jenkins-plugin-cli --plugins workflow-aggregator

# Configuration-as-code config
COPY casc.yaml /var/jenkins_home/casc.yaml
